name: Build & Release temporal-worker

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "**"
      - ".github/workflows/ryvn-temporal-worker-release.yaml"
  pull_request:
    branches:
      - "main"
    paths:
      - "**"

jobs:
  release:
    uses: ryvn-technologies/ryvn-build-action/.github/workflows/release.yml@v2
    with:
      service_name: temporal-worker
    permissions:
      contents: write
      id-token: write
    secrets:
      RYVN_CLIENT_ID: ${{ secrets.RYVN_CLIENT_ID }}
      RYVN_CLIENT_SECRET: ${{ secrets.RYVN_CLIENT_SECRET }}
